### ISSUE TITLE
Game Over Screen(Winning/Losing)

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#15]
ทำหน้าต่างในตอนที่เกมตัดสินผู้ชนะได้แล้ว

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/190087441-9e1cfac8-5e64-4396-94d4-6e3df65f1d3c.png)

**Comment by XeNoXTS** [comment]
แขนโดน Text อ่ะ

**Comment by XeNoXTS** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/110968217/191008438-e769517f-f080-4da6-a3ab-f0e6709f9ce5.png">
พอเกมจบแล้วมันกดไรไม่ได้เลยอ่ะ

**Comment by XeNoXTS** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/110968217/191348317-4161e725-9448-4771-ad24-3986d1b320cb.png">
