### ISSUE TITLE
แบ่งรายละเอียดการ present

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#2]
หัวข้อที่เรามีตอนนี้จะมี
-Gameplay
-แรงบันดาลใจ
-แนวเกม

**Comment by XeNoXTS** [comment]
เดี๋ยวเรานำเสนอเรื่องแนวกับแรงบันดาลใจเอง

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/189320306-c0eedb7b-ce2c-4292-92ad-eafcfe3fc69d.png)
หน้าแรกเริ่มตอนเข้ามาเอาเป็น แบบนี้เลยดีไหม แล้วค่อยใสหน้าเลือกสีหน้าถัดมา

**Comment by slyphstia** [comment]
ปาล์มทำหลอดเลือดตัวละครเสร็จหรือยัง

**Comment by slyphstia** [comment]
ปาล์มทำหลอดเลือดเสร็จยัง

**Comment by slyphstia** [comment]
ปาล์มทำหลอดเลือดตัวละครเสร็จยัง

**Comment by Goodl3oyZ** [comment]
![Start page](https://user-images.githubusercontent.com/110963173/189322650-6e6a26e7-1b49-4209-b937-8378002a0b32.png)
น่าถัดไป กูอยากได้ Graphic เลือกสีปะนี้ อะ ติว มึงลองทำให้หน่อยได้ไหม เดี๋วส่งไฟล์ไปให้

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/189323976-3846a6ff-a0d8-41d2-a236-d93b6a8ca765.png)

**Comment by XeNoXTS** [comment]
ยังไม่เสร็จๆ
