### ISSUE TITLE
Unique Player Skill

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#26]
ออกแบบยูนีคสกิลของแต่ละตัวละคร ให้แต่ละตัวละครมีสกิลอัลติเมทที่แตกต่างกัน

**Comment by XeNoXTS** [comment]
อัลติเราจะเอาเลือดลดเท่าไรใช้ได้ดีอ่ะ
คือเลือดมี 30 ใช่ป้ะ ถ้าแบบให้เกมนึงใช้ได้คนละ2ครั้ง ก็เอาเป็นต้องโดน 10 ฮิตมั้ย คือไม่นับดาเมจ นับแค่ฮิตพอ ไม่งั้นมันจะสาดอัลติแล้วโดนดาเมจเยอะละอีกฝั่งจะได้อัลติมาสวนอีก
ส่วนจะให้สกิลแรงเท่าไร ก็เอาเป็นดาเมจสัก 10 ละกัน

**Comment by XeNoXTS** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/110968217/191248290-5c261ca3-05c6-42f7-a4af-be31a4e338dd.png">
ทำ UI หลอดอัลติเมทพร้อมเขียนโปรแกรมแบบนับ Hit แล้ว
รอการ Design ท่าและ Animation ต่อไป

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/191326154-5fbf4ca5-45ef-4d2c-8173-786e0f71c5f9.png)
![image](https://user-images.githubusercontent.com/110963173/191326178-5b922554-b17b-4536-b4df-9c7fcf59fc1b.png)
![image](https://user-images.githubusercontent.com/110963173/191326213-7820e236-a415-4bfd-b7da-d3ab7a4df661.png)
![image](https://user-images.githubusercontent.com/110963173/191326466-82f40646-0953-46ef-8f4d-efa5aae893f7.png)
สกิลพิเศษ(อัลติ)เฉพาะของแต่ละสี(รูปที่แนบมาสีไม่ตรง)
1.สีเขียว คือ การด้อยค่าฝั่งตรงข้ามที่ได้คะแนน cal น้อยจนน่าดรอป
2.สีแดง คือ ท่า ปล่อยพลังใส่ฝั่งตรงข้าม
3.สีม่วง คือ การโจมตีโดยยื่นเกรดเอฟให้ฝั่งตรงข้าม
4.สีน้ำเงิน คือ การออกอาวุธโดยใช้ไม้ทีฟาดไปทีหัวของฝั่งตรงข้าม

**Comment by Goodl3oyZ** [comment]
โดยสกิลอัลติจะใช้ได้เมื่อหลอดอัลติ เต็มหลอดแล้วอัลติสร้างความเสียหายเท่ากับ 5
