### ISSUE TITLE
กดกระโดดไม่ได้

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#28]
กดกระโดดไม่ได้

**Comment by Goodl3oyZ** [comment]
เปลี่ยนการใช้ทักษะ เนื่องจากการกระโดดไม่ได้ช่วยให้เกมเพยนั้นมีความสนุก หรืออะไรเพิ่มขึ้น เราจึงเปลี่ยนเป็นทักษะ การ วิ่งเร็ว แทน โดยการกดปุ่ม2ปุ่มคือ ปุ่มเดินซ้าย/ขวา+ปุ่มw/mouse up
