### ISSUE TITLE
ความคืบหน้าตัวเกม

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#5]

**Comment by slyphstia** [comment]
ปัญหาปัจจุบัน
1.p2 เลือกสีม่วงไมไ่ด้
2.เตะตอนตั้งโล่แล้วยังโดนดาเมจ
3.กดย้ำๆจนจบเกมเมื่อเริ่มตาใหม่skillยังดีเลย์

**Comment by slyphstia** [comment]
สามารถต่อสู้กันได้
หน้าต่างUI60%
สามารถใช้มีดกับโล่ได้

**Comment by Goodl3oyZ** [comment]
![image](https://user-images.githubusercontent.com/110963173/189914820-38655f24-1fea-467b-890b-12f063fb0ae1.png)
![image](https://user-images.githubusercontent.com/110963173/189914854-2b3dfb6e-1ea4-4e5a-88ce-25ceb2487b46.png)
![image](https://user-images.githubusercontent.com/110963173/189914919-d88aa9dd-0d6e-4200-a50b-7aab04914338.png)

**Comment by XeNoXTS** [comment]
Planned Features
-Countdown Timer
-Player's Life
-Game Over Screen(Winning/Losing)
-Decorated UI
-New Background Stage
-Control Scheme

**Comment by slyphstia** [comment]
1.p2 เลือกสีม่วงไมไ่ด้ (fixed)
2.เตะตอนตั้งโล่แล้วยังโดนดาเมจ
3.กดย้ำๆจนจบเกมเมื่อเริ่มตาใหม่skillยังดีเลย์ (fixed)

**Comment by XeNoXTS** [comment]
ย้ายไปใช้การแยก Issues แทนการพิมพ์ใน issue เดียวกัน
