### ISSUE TITLE
คู่มือ

### ISSUE THREAD

**Issue by XeNoXTS** [XeNoXTS/Scratch-Project-Group-16-#6]
เขียนคู่มือแสดงรายละเอียด,วิธีเล่น ของตัวเกม

**Comment by XeNoXTS** [comment]
เลื่อนกำหนดการนะ
เอาไว้ทำหลังส่งโครงงานแล้ว

**Comment by slyphstia** [comment]
![image](https://user-images.githubusercontent.com/110963884/191433663-6a6fa92e-ec43-46b7-a930-ffb89d2e1bf2.png)
![image](https://user-images.githubusercontent.com/110963884/191433710-be8531e4-7ccb-43bb-a607-4f2f26e58166.png)
![image](https://user-images.githubusercontent.com/110963884/191433742-415dc4f3-c706-4a71-88f1-8ba1138b85b3.png)

**Comment by slyphstia** [comment]
เสร็จละจ้า
